### ISSUE TITLE
Hello All; I'm writing ORM based on sqlite and i need the transpiler to support annotation metadata. Thanks

### ISSUE THREAD

**Issue by PierreLouer** [fuse-open/transpiler#4]

**Comment by mortend** [comment]
We added decorators support in https://github.com/fuse-open/transpiler/pull/2.

Can you elaborate on what needs to be supported by transpiler?

**Comment by PierreLouer** [comment]
Hello @mortend  Sorry for the late reply. In fact actually the transpiler supports decorators, but when i added metadata as below, it does not work


    import "reflect-metadata";
    const formatMetadataKey = Symbol("format");

    function format(formatString: string) {
        return Reflect.metadata(formatMetadataKey, formatString);
    }

    function getFormat(target: any, propertyKey: string) {
        return Reflect.getMetadata(formatMetadataKey, target, propertyKey);
    }

    class Greeter {
        @format("Hello, %s")
        greeting: string;

        constructor(message: string) {
            this.greeting = message;
        }

        greet() {
            let formatString = getFormat(this, "greeting");
            console.log('metadata => ' + formatString)
            return formatString.replace("%s", this.greeting);
        }
    }

    console.log('Greeting => ' + new Greeter('Pierre').greet())

Output of app
    
    metadata => undefined
    Error: TypeError: Cannot read property 'replace' of undefined: Uncaught TypeError: Cannot read property 'replace' of undefined
    	In: Fuse.Scripting.DiagnosticSubject
    	Fuse: Index.js:206

Outout of ts-node
    
    metadata => Hello, %s
    Greeting => Hello, Pierre

I suggest in this case to add metadata support by plugin such as [babel-plugin-transform-typescript-metadata](https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata).

**Comment by mortend** [comment]
Aha, I see. Thanks for clarifying. I think it should be possible for us to support metadata as well.

**Comment by mortend** [comment]
@PierreLouer Syntax works now and the metadata is persisted in generated output code.

It looks like we need to polyfill `reflect-metadata` to make this fully work in Fuse. When trying out the new version of transpiler in Fuse Studio I get the following errors.

```
[Viewport]: Error: : Uncaught require(): module not found: reflect-metadata
	In: Fuse.Scripting.DiagnosticSubject
	Fuse: Logic.js:8
```

```
[Viewport]: Error: TypeError: Reflect.metadata is not a function: Uncaught TypeError: Reflect.metadata is not a function
	In: Fuse.Scripting.DiagnosticSubject
	Fuse: Logic.js:54
```

You can install the new version of transpiler and try it out. If you are using Fuse Studio I think you can `cd` into your `@fuse-x/studio` module directory and install it there.

```
npm i @fuse-open/transpiler
```

**Comment by PierreLouer** [comment]
Hello @mortend I still have the same error
